language: python
python:
  - "2.7"
install:
  - "sudo apt-get update"
  - "sudo echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections"
  - "sudo apt-get install ttf-mscorefonts-installer"
  - "sudo apt-get install texlive"
  - "sudo apt-get install texlive-xetex"
  - "sudo apt-get install texlive-lang-french"
  - "sudo apt-get install texlive-latex-extra"
  - "sudo mkdir -p ~/cabal/bin"
  - "sudo mkdir -p ~/cabal/bin/templates"
  - "sudo wget -P ~/cabal/bin https://dl.dropboxusercontent.com/u/18967337/pandoc"
  - "sudo wget -P ~/cabal/bin/templates https://dl.dropboxusercontent.com/u/14517385/dev/default.epub"
  - "sudo wget -P ~/cabal/bin/templates https://dl.dropboxusercontent.com/u/14517385/dev/default.html"
  - "sudo wget -P ./templates https://dl.dropboxusercontent.com/u/14517385/dev/default.epub"
  - "sudo wget -P ./templates https://dl.dropboxusercontent.com/u/14517385/dev/default.html"
  - "sudo chmod u+x,g+x,o+x ~/cabal/bin/pandoc"
  - "sudo pandoc -v"
  - "export PATH=$PATH:~/cabal/bin"
  - "sudo apt-get --reinstall install -qq language-pack-fr"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: 
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
